"""
Gradio Frontend for YouTube to Book Summary Converter
Deploy on Hugging Face Spaces
"""
import os
import gradio as gr
from datetime import datetime
from typing import Optional, Tuple
import tempfile
import textwrap

# PDF and Word generation
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

# Import our modules
from config import config
from summarizer import YouTubeBookSummarizer, create_summarizer
from youtube_transcript import YouTubeExtractor, extract_transcript


def create_pdf(summary: str, video_title: str, video_id: str, url: str, output_path: str) -> str:
    """Create a PDF file with the book summary."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor='#333333'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceBefore=20,
        spaceAfter=10,
        textColor='#555555'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )
    
    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor='#666666',
        spaceAfter=6
    )
    
    story = []
    
    # Title
    story.append(Paragraph(f"📚 {video_title}", title_style))
    story.append(Spacer(1, 20))
    
    # Metadata
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", meta_style))
    story.append(Paragraph(f"<b>Video ID:</b> {video_id}", meta_style))
    story.append(Paragraph(f"<b>Source:</b> {url}", meta_style))
    story.append(Spacer(1, 30))
    
    # Horizontal line simulation
    story.append(Paragraph("_" * 80, meta_style))
    story.append(Spacer(1, 20))
    
    # Process summary content
    lines = summary.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 10))
            continue
        
        # Check if it's a heading (starts with # or ##)
        if line.startswith('## '):
            story.append(Paragraph(line[3:], heading_style))
        elif line.startswith('# '):
            story.append(Paragraph(line[2:], heading_style))
        elif line.startswith('**') and line.endswith('**'):
            # Bold text as subheading
            story.append(Paragraph(line, heading_style))
        else:
            # Escape HTML special characters
            line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            # Convert markdown bold to HTML bold
            line = line.replace('**', '<b>', 1)
            line = line.replace('**', '</b>', 1)
            while '**' in line:
                line = line.replace('**', '<b>', 1)
                line = line.replace('**', '</b>', 1)
            story.append(Paragraph(line, body_style))
    
    story.append(Spacer(1, 30))
    story.append(Paragraph("_" * 80, meta_style))
    story.append(Spacer(1, 10))
    story.append(Paragraph("<i>Generated by YouTube to Book Summary Converter</i>", meta_style))
    
    doc.build(story)
    return output_path


def create_word_doc(summary: str, video_title: str, video_id: str, url: str, output_path: str) -> str:
    """Create a Word document with the book summary."""
    doc = Document()
    
    # Title
    title = doc.add_heading(f"📚 {video_title}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    doc.add_paragraph()
    meta_para = doc.add_paragraph()
    meta_para.add_run("Generated: ").bold = True
    meta_para.add_run(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    
    meta_para2 = doc.add_paragraph()
    meta_para2.add_run("Video ID: ").bold = True
    meta_para2.add_run(video_id)
    
    meta_para3 = doc.add_paragraph()
    meta_para3.add_run("Source: ").bold = True
    meta_para3.add_run(url)
    
    # Horizontal line
    doc.add_paragraph("─" * 50)
    
    # Process summary content
    lines = summary.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        # Check if it's a heading
        if line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('**') and line.endswith('**'):
            # Bold paragraph as subheading
            para = doc.add_paragraph()
            run = para.add_run(line.strip('*'))
            run.bold = True
        else:
            # Regular paragraph - handle bold text
            para = doc.add_paragraph()
            # Simple handling of bold markers
            parts = line.split('**')
            for i, part in enumerate(parts):
                if i % 2 == 1:  # Odd indices are bold
                    run = para.add_run(part)
                    run.bold = True
                else:
                    para.add_run(part)
    
    # Footer
    doc.add_paragraph()
    doc.add_paragraph("─" * 50)
    footer = doc.add_paragraph()
    run = footer.add_run("Generated by YouTube to Book Summary Converter")
    run.italic = True
    
    doc.save(output_path)
    return output_path


def create_transcript_file(transcript_text: str, video_title: str, video_id: str, url: str, output_path: str) -> str:
    """Create a text file with the transcript."""
    content = f"""# 📝 Transcript: {video_title}

**Video ID:** {video_id}
**Source:** {url}
**Extracted:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

{'─' * 50}

{transcript_text}

{'─' * 50}

*Extracted by YouTube to Book Summary Converter*
"""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return output_path


def process_video(
    url: str,
    api_key: Optional[str] = None,
    language: str = "en",
    progress: gr.Progress = gr.Progress()
) -> Tuple[str, str, str, str, str, str, str]:
    """
    Process a YouTube video and generate summary.
    
    Args:
        url: YouTube video URL
        api_key: Optional Groq API key (falls back to env variable)
        language: Transcript language
        progress: Gradio progress tracker
        
    Returns:
        Tuple of (summary, video_info, status_message, pdf_file, word_file, md_file, transcript_file)
    """
    if not url or not url.strip():
        return "", "", "⚠️ Please enter a YouTube URL", None, None, None, None
    
    # Validate URL
    extractor = YouTubeExtractor()
    video_id = extractor.extract_video_id(url)
    
    if not video_id:
        return "", "", "❌ Invalid YouTube URL. Please check and try again.", None, None, None, None
    
    try:
        # Step 1: Extract transcript (20%)
        progress(0.1, desc="📥 Extracting transcript...")
        
        transcript_result = extract_transcript(url, language)
        
        if not transcript_result['success']:
            return "", "", f"❌ Failed to extract transcript: {transcript_result['error']}", None, None, None, None
        
        metadata = transcript_result['metadata']
        video_title = metadata.get('title', f'Video {video_id}')
        transcript_text = transcript_result.get('transcript', '')
        
        # Step 2: Get video info (30%)
        progress(0.3, desc="📋 Processing video information...")
        
        video_info = f"""### 📹 Video Information
        
**Title:** {video_title}

**Video ID:** {video_id}

**Language:** {metadata.get('language', 'en')}

**Transcript Length:** {metadata.get('transcript_length', 'N/A'):,} characters
"""
        
        # Step 3: Generate summary (50-90%)
        progress(0.5, desc="🤖 Generating AI summary...")
        
        # Use provided API key or fall back to environment
        effective_api_key = api_key.strip() if api_key and api_key.strip() else None
        
        summarizer = create_summarizer(
            api_key=effective_api_key,
            model=None
        )
        
        result = summarizer.summarize(
            url=url,
            language=language,
            save_output=False,  # Don't save files in Gradio
            verbose=False
        )
        
        if not result['success']:
            error_msg = result.get('error', 'Unknown error')
            if 'rate limit' in error_msg.lower() or 'quota' in error_msg.lower():
                return "", video_info, f"⏳ API rate limit reached. Please try with your own API key or wait a moment.\n\nError: {error_msg}", None, None, None, None
            return "", video_info, f"❌ Failed to generate summary: {error_msg}", None, None, None, None
        
        # Step 4: Complete (100%)
        progress(1.0, desc="✅ Complete!")
        
        summary = result['summary']
        usage = result.get('metadata', {}).get('usage', {})
        
        status = f"""✅ **Summary Generated Successfully!**

📊 **Usage Statistics:**
- Tokens Used: {usage.get('total_tokens', 'N/A'):,}
- Estimated Cost: ${usage.get('estimated_cost_usd', 0):.4f}
- Model: {result.get('metadata', {}).get('model', 'N/A')}
"""
        
        # Create downloadable files
        pdf_file, word_file, md_file, transcript_file = None, None, None, None
        temp_dir = tempfile.gettempdir()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c for c in video_title if c.isalnum() or c in (' ', '-', '_')).rstrip()
        
        try:
            # Create PDF
            pdf_path = os.path.join(temp_dir, f"book_summary_{safe_title}_{timestamp}.pdf")
            pdf_file = create_pdf(summary, video_title, video_id, url, pdf_path)
        except Exception as e:
            print(f"Warning: Could not create PDF file: {e}")
        
        try:
            # Create Word document
            word_path = os.path.join(temp_dir, f"book_summary_{safe_title}_{timestamp}.docx")
            word_file = create_word_doc(summary, video_title, video_id, url, word_path)
        except Exception as e:
            print(f"Warning: Could not create Word file: {e}")
        
        try:
            # Create Markdown file
            md_path = os.path.join(temp_dir, f"book_summary_{safe_title}_{timestamp}.md")
            md_content = f"""# 📚 {video_title}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Video ID:** {video_id}  
**Source:** {url}

---

{summary}

---

*Generated by YouTube to Book Summary Converter*
"""
            with open(md_path, 'w', encoding='utf-8') as f:
                f.write(md_content)
            md_file = md_path
        except Exception as e:
            print(f"Warning: Could not create Markdown file: {e}")
        
        try:
            # Create Transcript file
            transcript_path = os.path.join(temp_dir, f"transcript_{safe_title}_{timestamp}.txt")
            transcript_file = create_transcript_file(transcript_text, video_title, video_id, url, transcript_path)
        except Exception as e:
            print(f"Warning: Could not create transcript file: {e}")
        
        return summary, video_info, status, pdf_file, word_file, md_file, transcript_file
        
    except Exception as e:
        error_str = str(e)
        if 'api_key' in error_str.lower() or 'unauthorized' in error_str.lower():
            return "", "", f"🔑 **API Key Error:** Please provide a valid Groq API key.\n\nDetails: {error_str}", None, None, None, None
        return "", "", f"❌ **Error:** {error_str}", None, None, None, None


# Create the Gradio interface
with gr.Blocks(title="YouTube to Book Summary") as app:
    
    # Header
    gr.Markdown("""
    # 📚 YouTube to Book Summary Converter
    
    Transform any YouTube video into a comprehensive, book-style summary using AI (Groq LLM).
    """)
    
    # Main content
    with gr.Row():
        with gr.Column(scale=2):
            # Input section
            gr.Markdown("### 🎬 Video Input")
            
            url_input = gr.Textbox(
                label="YouTube URL",
                placeholder="https://www.youtube.com/watch?v=...",
                lines=1,
                max_lines=1
            )
            
            with gr.Accordion("⚙️ Advanced Settings", open=False):
                api_key_input = gr.Textbox(
                    label="Groq API Key (Optional)",
                    placeholder="Leave empty to use default key",
                    type="password",
                    lines=1
                )
                
                language_input = gr.Dropdown(
                    label="Transcript Language",
                    choices=["en", "es", "fr", "de", "it", "pt", "ja", "ko", "zh"],
                    value="en",
                    interactive=True
                )
                
                gr.Markdown("""
                💡 **Tip:** If the default API key is rate-limited, you can:
                1. Get a free API key from [console.groq.com](https://console.groq.com/)
                2. Paste it above to continue using the app
                """)
            
            generate_btn = gr.Button(
                "🚀 Generate Summary",
                variant="primary"
            )
            
            # Status output
            status_output = gr.Markdown(
                label="Status"
            )
            
            # Video info
            video_info_output = gr.Markdown(
                label="Video Information"
            )
        
        with gr.Column(scale=3):
            # Summary output
            summary_output = gr.Markdown(
                label="Generated Summary"
            )
            
            # Download buttons section
            gr.Markdown("### 📥 Download Options")
            with gr.Row():
                pdf_download = gr.DownloadButton(
                    label="📄 PDF",
                    variant="secondary",
                    visible=True
                )
                word_download = gr.DownloadButton(
                    label="📝 Word",
                    variant="secondary",
                    visible=True
                )
                md_download = gr.DownloadButton(
                    label="📋 Markdown",
                    variant="secondary",
                    visible=True
                )
                transcript_download = gr.DownloadButton(
                    label="📜 Transcript",
                    variant="secondary",
                    visible=True
                )
    
    # Examples
    gr.Examples(
        examples=[
            ["https://www.youtube.com/watch?v=dQw4w9WgXcQ"],
            ["https://www.youtube.com/watch?v=jNQXAC9IVRw"],
            ["https://youtu.be/aircAruvnKk"],
        ],
        inputs=[url_input],
        label="📝 Example Videos (Try these!)"
    )
    
    # Footer
    gr.Markdown("""
    ---
    **Powered by Groq LLM** | Built with ❤️ using Gradio
    
    Transform YouTube videos into comprehensive book-style summaries
    """)
    
    # Event handlers
    generate_btn.click(
        fn=process_video,
        inputs=[url_input, api_key_input, language_input],
        outputs=[summary_output, video_info_output, status_output, pdf_download, word_download, md_download, transcript_download],
        api_name="generate"
    )
    
    # Also allow Enter key to submit
    url_input.submit(
        fn=process_video,
        inputs=[url_input, api_key_input, language_input],
        outputs=[summary_output, video_info_output, status_output, pdf_download, word_download, md_download, transcript_download]
    )


if __name__ == "__main__":
    # For local development
    app.launch(
        server_name="0.0.0.0",
        server_port=7860,
        share=False,
        theme=gr.themes.Soft(
            primary_hue="purple",
            secondary_hue="blue",
            neutral_hue="slate",
        )
    )
